### ISSUE TITLE
temporary version is too restrictive

### ISSUE THREAD

**Issue by NCrashed** [fujimura/hi#58]
I have problems with building the last version with stack, need just to change `==` to `>=` for:
```
temporary ==1.2.0.3
```

**Comment by debug-ito** [comment]
I have the same problem. Is it necessary to set it too restrictive?

**Comment by fujimura** [comment]
It could be >= 1.2.0.3. I'm on this now.

**Comment by fujimura** [comment]
Just uploaded hi-1.2.0.1, which depends on temporary >=1.2.0.3.
https://hackage.haskell.org/package/hi-1.2.0.1

Thanks for reporting this!

**Comment by debug-ito** [comment]
Thanks!
