### ISSUE TITLE
Upload master to hackage

### ISSUE THREAD

**Issue by debug-ito** [fujimura/hi#63]
Latest version of hi in hackage (1.2.0.1) is incompatible with optparse-applicative >= 0.13, so it's difficult to build it with recent stack snapshots.

Could you upload the master version in this repository to hackage? Thanks in advance.

**Comment by adetokunbo** [comment]
@debug-ito @fujimara: I thought a new release might be needed as well, hence #62

**Comment by adetokunbo** [comment]
@fujimura: This is also the same issue as #61.  It was fixed in #60, it just requires a new release.
If you are busy, please add me as a package maintainer on hackage (I am [adetokunbo](https://hackage.haskell.org/user/adetokunbo) there as well), and I will upload a release on your behalf.

**Comment by debug-ito** [comment]
Oops, this was  a duplicate of #62.

**Comment by fujimura** [comment]
Just uploaded 1.2.0.2  which is compatible with optparse-applicative >= 0.13 to hackage. I confirmed that hi 1.2.0.2 can be installed with GHC 8.4.3 & cabal-install 2.2.0.0.

Let me know if you find further issues. Thanks for reporting!

**Comment by debug-ito** [comment]
Thanks!
